import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>BatDrobe.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={styles.fullWidth}>
          {/* <Image
            src="/batman.jpg"
            alt="homepage-image"
            width={1000}
            height={1000}
          /> */}
        
        <img src="/batarang-background.jpg" ></img>
        </div>
      </main>
    </>
  );
}
